/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_80001E8();
void __fastcall __noreturn sub_80001FE(int a1, int a2);
signed __int64 sub_8000224();
int sub_8003C1A();
int sub_8003DE8();
unsigned int sub_8003E50();
_WORD *__fastcall sub_8003F9A(int a1, int a2, int a3, int a4);
unsigned __int8 *__fastcall sub_8003FF8(int a1, int a2, int a3);
int sub_80041C8();
int __fastcall sub_800428A(int a1, int a2, int a3);
unsigned __int8 *sub_8004348();
_DWORD *__fastcall sub_80043C4(_DWORD *result);
unsigned int *__fastcall sub_8004508(unsigned int *result, unsigned int *a2);
int *__fastcall sub_800455E(int *result, int a2);
signed int sub_8004614();
signed int sub_800463E();
signed int sub_800467E();
int sub_8004690();
int __fastcall sub_800469A(int result);
int __fastcall sub_80046CC(int result);
int __fastcall sub_80046FE(int result);
int __fastcall sub_8004A28(int a1);
int __fastcall sub_8004AB6(int a1, int a2);
int __fastcall sub_8004B66(int a1, int a2, int a3);
int __fastcall sub_8004B84(int a1, int a2);
int __fastcall sub_8004BF0(int a1, int a2, int a3);
int __fastcall sub_8004C36(int a1, int a2, int a3, int a4, int a5);
int __fastcall sub_8004D8A(int a1, int a2, int a3, unsigned __int16 a4, unsigned __int16 a5);
int __fastcall sub_80050B0(int a1, int a2, int a3, unsigned __int16 a4, unsigned __int16 a5);
int __fastcall sub_80050D4(int a1, int a2);
int __fastcall sub_80054BA(int a1, int a2, int a3, int a4);
signed int __fastcall sub_8005572(int a1, int a2, int a3, int a4, __int16 a5);
int __fastcall sub_8005758(int a1, int a2, char a3, int a4, int a5);
signed int __fastcall sub_8005890(int a1, int a2);
int __fastcall sub_80059CA(int a1, int a2, char a3, int a4, int a5, int a6);
int __fastcall sub_8005C1C(int a1);
int sub_8005C74();
int sub_8005CD4();
int sub_8005D34();
int sub_8005D94();
int sub_8005DF4();
int sub_8005E78();
int sub_8005ED8();
int sub_8005F38();
int sub_8005F98();
int sub_8005FF8();
signed int __fastcall sub_80060F4(signed int result);
_DWORD *__fastcall sub_800613E(_DWORD *result);
_QWORD *__fastcall sub_8006320(_QWORD *result);
_DWORD *__fastcall sub_80064AA(_DWORD *result);
signed int __fastcall sub_8006950(signed int result);
signed int __fastcall sub_800699A(signed int result);
_DWORD *__fastcall sub_80069E4(_DWORD *result);
int __fastcall sub_8006AF8(int result);
signed int sub_80075B4();
int __fastcall sub_80075F4(int result);
BOOL __fastcall sub_800763A(int a1);
BOOL sub_8007672();
unsigned int __fastcall sub_80076C4(int a1, int a2);
int __fastcall sub_80076DC(int result);
unsigned int __fastcall sub_80076E2(int a1);
int sub_80076F4();
unsigned int __fastcall sub_80076FE(int a1);
unsigned int __fastcall sub_8007710(int a1);
unsigned int __fastcall sub_8007722(int a1);
unsigned int __fastcall sub_8007756(int a1);
int __fastcall sub_8007768(int result);
int __fastcall sub_8007794(int result);
int __fastcall sub_800779A(int result);
int __fastcall sub_80077A6(int result);
_DWORD *__fastcall sub_80077AE(_DWORD *result);
int __fastcall sub_800786E(int result, int a2);
int __fastcall sub_8007888(int result, int a2);
int __fastcall sub_80078A2(int result, int a2);
int __fastcall sub_80078BC(int result, int a2);
int __fastcall sub_80078D6(int result, int a2);
int __fastcall sub_80078F0(int result);
int __fastcall sub_8007958(int a1);
unsigned int __fastcall sub_80079A6(_DWORD *a1, int a2);
int __fastcall sub_80079FE(int result, int a2);
int __fastcall sub_8007A14(int result, int a2);
int __fastcall sub_8007A42(int result);
BOOL __fastcall sub_8007A4C(int a1);
int __fastcall sub_8007A60(int result);
BOOL __fastcall sub_8007A6A(int a1);
int __fastcall sub_8007A7E(int result, int a2);
int __fastcall sub_8007AD6(_DWORD *a1, signed int a2, signed int a3, int a4);
int __fastcall sub_8007BA4(int a1);
BOOL __fastcall sub_8007D60(_DWORD *a1, int a2);
unsigned int __fastcall sub_8007E68(int *a1, _BYTE *a2);
unsigned int __fastcall sub_8008006(unsigned int result, int a2);
int __fastcall sub_8008090(int result, int a2);
int __fastcall sub_8008100(int a1);
__int16 *__fastcall sub_80082A8(__int16 *result, int a2);
int __fastcall sub_800858C(int result, __int16 a2);
int __fastcall sub_80085A6(int result, int a2, int a3, int a4);
int __fastcall sub_8008628(int result, __int16 a2);
int __fastcall sub_800863A(int result, int a2, int a3, int a4);
int __fastcall sub_80086B4(int result, __int16 a2);
int __fastcall sub_80086CE(int result, int a2, int a3, int a4);
int __fastcall sub_8008750(int result, __int16 a2);
int __fastcall sub_8008762(int result, int a2, int a3, int a4);
_WORD *__fastcall sub_8008960(_WORD *result, int a2);
int __fastcall sub_8008996(int result, int a2, int a3);
int __fastcall sub_80089C8(int result);
int __fastcall sub_80089D4(int result, __int16 a2);
int __fastcall sub_8008A3C(int result, __int16 a2, __int16 a3, __int16 a4);
_WORD *__fastcall sub_8008B60(_WORD *result, int a2);
int __fastcall sub_8008EEC(int result, __int16 a2);
int __fastcall sub_8008F38(int result);
BOOL __fastcall sub_8009004(int a1);
int __fastcall sub_8009026(int result);
int sub_8009038();
int __fastcall sub_80090FC(int a1);
int __fastcall sub_8009124(int result);
signed int sub_800916E();
signed int sub_800919E();
signed int sub_8009250();
BOOL sub_80092BA();
int __fastcall sub_80096B8(int result);
unsigned __int8 *__fastcall sub_80096C2(unsigned __int8 *result);
int __fastcall sub_8009758(int result);
unsigned int __fastcall sub_800981A(_WORD *a1, _WORD *a2);
int __fastcall sub_8009932(int result, int a2);
int *__fastcall sub_800994A(int *a1, unsigned __int8 a2, int a3);
int __fastcall sub_8009A14(int a1);
BOOL __fastcall sub_8009B14(unsigned __int16 *a1, __int16 a2);
int __fastcall sub_8009BB2(int result);
__int16 __fastcall sub_8009C68(__int16 result, int a2);
int sub_8009C82();
int sub_8009C94();
int sub_8009CD4();
int sub_8009D20();
int sub_8009D30();
int __fastcall sub_8009DC2(int result);
char __fastcall sub_8009DD4(char result);
signed int sub_8009DF6();
char __fastcall sub_8009DFE(char result);
int __fastcall sub_8009E0A(int result);
int sub_8009E20();
signed int sub_8009E90();
void __noreturn sub_8009E98();

//-------------------------------------------------------------------------
// Data declarations

__int16 word_8009EA6[] = { 0 }; // weak


//----- (080001E8) --------------------------------------------------------
void sub_80001E8()
{
  ;
}

//----- (080001FE) --------------------------------------------------------
void __fastcall __noreturn sub_80001FE(int a1, int a2)
{
  sub_80001E8();
  sub_8009E98();
}

//----- (08000224) --------------------------------------------------------
signed __int64 sub_8000224()
{
  return 2305853798708413392LL;
}

//----- (08003C1A) --------------------------------------------------------
int sub_8003C1A()
{
  if ( !(((unsigned int)MEMORY[0x20000049] >> 6) & 1) )
    sub_8009DFE(127);
  return sub_8009E20();
}

//----- (08003DE8) --------------------------------------------------------
int sub_8003DE8()
{
  int result; // r0

  sub_80075B4();
  sub_80075F4(0x10000);
  while ( !sub_8007672() )
    ;
  sub_80076FE(0);
  sub_8007722(0);
  sub_8007710(1024);
  sub_80090FC(2);
  sub_8009124(16);
  sub_80076C4(0x10000, 1835008);
  sub_80076DC(1);
  while ( !sub_800763A(57) )
    ;
  sub_80076E2(2);
  do
    result = sub_80076F4();
  while ( result != 8 );
  return result;
}

//----- (08003E50) --------------------------------------------------------
unsigned int sub_8003E50()
{
  __int16 v1; // [sp+0h] [bp-8h]
  char v2; // [sp+2h] [bp-6h]
  char v3; // [sp+3h] [bp-5h]

  sub_8007888(125, 1);
  sub_8008006(0x300200u, 1);
  v1 = -3200;
  v3 = 16;
  v2 = 3;
  sub_8007E68((int *)0x40010800, &v1);
  v1 = 127;
  v3 = 0;
  sub_8007E68((int *)0x40010800, &v1);
  v1 = 1024;
  v3 = 4;
  sub_8007E68((int *)0x40010800, &v1);
  v1 = 2048;
  v3 = 72;
  sub_8007E68((int *)0x40010800, &v1);
  v1 = -4;
  v3 = 16;
  v2 = 3;
  sub_8007E68((int *)0x40010C00, &v1);
  v1 = 3;
  v3 = 0;
  sub_8007E68((int *)0x40010C00, &v1);
  v1 = 7731;
  v3 = 16;
  v2 = 3;
  sub_8007E68((int *)0x40011000, &v1);
  v1 = 4;
  v3 = 0;
  sub_8007E68((int *)0x40011000, &v1);
  v1 = -7736;
  v3 = 72;
  sub_8007E68((int *)0x40011000, &v1);
  v1 = 7934;
  v3 = 16;
  v2 = 3;
  sub_8007E68((int *)0x40011400, &v1);
  v1 = 256;
  v3 = 4;
  sub_8007E68((int *)0x40011400, &v1);
  v1 = -8191;
  v3 = 72;
  sub_8007E68((int *)0x40011400, &v1);
  v1 = -1;
  v3 = 16;
  v2 = 3;
  return sub_8007E68((int *)0x40011800, &v1);
}

//----- (08003F9A) --------------------------------------------------------
_WORD *__fastcall sub_8003F9A(int a1, int a2, int a3, int a4)
{
  __int16 v5; // [sp+0h] [bp-10h]
  __int16 v6; // [sp+2h] [bp-Eh]
  __int16 v7; // [sp+4h] [bp-Ch]
  __int16 v8; // [sp+6h] [bp-Ah]
  int v9; // [sp+8h] [bp-8h]

  v9 = a4;
  sub_80078A2(1, 1);
  sub_8008100(0x40000000);
  sub_80089C8(0x40000000);
  v5 = 35;
  v8 = 0;
  v6 = 0;
  v7 = 98;
  sub_80082A8((__int16 *)0x40000000, (int)&v5);
  sub_8008EEC(0x40000000, 1);
  sub_8008B60((_WORD *)0x40000000, 0);
  sub_8008996(0x40000000, 1, 1);
  return sub_8008960((_WORD *)0x40000000, 1);
}

//----- (08003FF8) --------------------------------------------------------
unsigned __int8 *__fastcall sub_8003FF8(int a1, int a2, int a3)
{
  int v4; // [sp+0h] [bp-10h]
  int v5; // [sp+4h] [bp-Ch]
  char v6; // [sp+8h] [bp-8h]
  char v7; // [sp+9h] [bp-7h]
  char v8; // [sp+Ah] [bp-6h]
  char v9; // [sp+Bh] [bp-5h]

  v5 = a3;
  sub_80096B8(1280);
  v6 = 28;
  v7 = 0;
  v8 = 1;
  v9 = 1;
  sub_80096C2((unsigned __int8 *)&v6);
  sub_8007888(1, 1);
  sub_8008090(3, 0);
  v4 = 1;
  LOWORD(v5) = 3072;
  BYTE2(v5) = 1;
  sub_8008F38((int)&v4);
  sub_8008090(3, 15);
  v4 = 0x8000;
  LOWORD(v5) = 3072;
  BYTE2(v5) = 1;
  sub_8008F38((int)&v4);
  sub_8008090(3, 8);
  v4 = 256;
  LOWORD(v5) = 2048;
  BYTE2(v5) = 1;
  sub_8008F38((int)&v4);
  v6 = 6;
  v7 = 2;
  v8 = 1;
  v9 = 1;
  sub_80096C2((unsigned __int8 *)&v6);
  v6 = 40;
  v7 = 2;
  v8 = 2;
  v9 = 1;
  sub_80096C2((unsigned __int8 *)&v6);
  v6 = 23;
  v7 = 2;
  v8 = 0;
  v9 = 1;
  return sub_80096C2((unsigned __int8 *)&v6);
}

//----- (080041C8) --------------------------------------------------------
int sub_80041C8()
{
  char v1; // [sp+4h] [bp-1Ch]
  char v2; // [sp+5h] [bp-1Bh]
  char v3; // [sp+6h] [bp-1Ah]
  char v4; // [sp+7h] [bp-19h]
  int v5; // [sp+8h] [bp-18h]
  __int16 v6; // [sp+Ch] [bp-14h]
  __int16 v7; // [sp+Eh] [bp-12h]
  __int16 v8; // [sp+10h] [bp-10h]
  __int16 v9; // [sp+12h] [bp-Eh]
  __int16 v10; // [sp+14h] [bp-Ch]
  __int16 v11; // [sp+18h] [bp-8h]
  char v12; // [sp+1Ah] [bp-6h]
  char v13; // [sp+1Bh] [bp-5h]

  sub_8007888(0x4000, 1);
  v11 = 512;
  v13 = 24;
  v12 = 3;
  sub_8007E68((int *)0x40010800, &v11);
  v11 = 1024;
  v13 = 4;
  sub_8007E68((int *)0x40010800, &v11);
  v5 = 19200;
  v6 = 0;
  v7 = 0;
  v8 = 0;
  v10 = 0;
  v9 = 12;
  sub_800981A((_WORD *)0x40013800, &v5);
  v1 = 37;
  v2 = 3;
  v3 = 3;
  v4 = 1;
  sub_80096C2((unsigned __int8 *)&v1);
  sub_800994A((int *)0x40013800, 0x25u, 1);
  return sub_8009932(1073821696, 1);
}

//----- (0800428A) --------------------------------------------------------
int __fastcall sub_800428A(int a1, int a2, int a3)
{
  int v4; // [sp+0h] [bp-10h]
  int v5; // [sp+4h] [bp-Ch]
  char v6; // [sp+8h] [bp-8h]
  char v7; // [sp+9h] [bp-7h]
  char v8; // [sp+Ah] [bp-6h]
  char v9; // [sp+Bh] [bp-5h]

  v5 = a3;
  v6 = 3;
  v7 = 2;
  v8 = 1;
  v9 = 1;
  sub_80096C2((unsigned __int8 *)&v6);
  v6 = 41;
  v7 = 1;
  v8 = 2;
  v9 = 1;
  sub_80096C2((unsigned __int8 *)&v6);
  sub_8009026(0x20000);
  LOWORD(v5) = 2048;
  v4 = 0x20000;
  BYTE2(v5) = 1;
  return sub_8008F38((int)&v4);
}

//----- (08004348) --------------------------------------------------------
unsigned __int8 *sub_8004348()
{
  char v1; // [sp+0h] [bp-8h]
  char v2; // [sp+1h] [bp-7h]
  char v3; // [sp+2h] [bp-6h]
  char v4; // [sp+3h] [bp-5h]

  v1 = 0;
  v4 = 1;
  v2 = 2;
  v3 = 3;
  return sub_80096C2((unsigned __int8 *)&v1);
}

//----- (080043C4) --------------------------------------------------------
_DWORD *__fastcall sub_80043C4(_DWORD *result)
{
  *result &= 0xFFFEu;
  *result = 0;
  result[1] = 0;
  result[2] = 0;
  result[3] = 0;
  if ( result == (_DWORD *)1073872904 )
  {
    MEMORY[0x40020004] |= 0xFu;
  }
  else if ( result == (_DWORD *)1073872924 )
  {
    MEMORY[0x40020004] |= 0xF0u;
  }
  else if ( result == (_DWORD *)1073872944 )
  {
    MEMORY[0x40020004] |= 0xF00u;
  }
  else if ( result == (_DWORD *)1073872964 )
  {
    MEMORY[0x40020004] |= 0xF000u;
  }
  else if ( result == (_DWORD *)1073872984 )
  {
    MEMORY[0x40020004] |= 0xF0000u;
  }
  else if ( result == (_DWORD *)1073873004 )
  {
    MEMORY[0x40020004] |= 0xF00000u;
  }
  else if ( result == (_DWORD *)1073873024 )
  {
    MEMORY[0x40020004] |= 0xF000000u;
  }
  else if ( result == (_DWORD *)1073873928 )
  {
    MEMORY[0x40020404] |= 0xFu;
  }
  else if ( result == (_DWORD *)1073873948 )
  {
    MEMORY[0x40020404] |= 0xF0u;
  }
  else if ( result == (_DWORD *)1073873968 )
  {
    MEMORY[0x40020404] |= 0xF00u;
  }
  else if ( result == (_DWORD *)1073873988 )
  {
    MEMORY[0x40020404] |= 0xF000u;
  }
  else if ( result == (_DWORD *)1073874008 )
  {
    MEMORY[0x40020404] |= 0xF0000u;
  }
  return result;
}

//----- (08004508) --------------------------------------------------------
unsigned int *__fastcall sub_8004508(unsigned int *result, unsigned int *a2)
{
  *result = *result & 0xFFFF800F | a2[2] | a2[8] | a2[4] | a2[5] | a2[6] | a2[7] | a2[9] | a2[10];
  result[1] = a2[3];
  result[2] = *a2;
  result[3] = a2[1];
  return result;
}

//----- (0800455E) --------------------------------------------------------
int *__fastcall sub_800455E(int *result, int a2)
{
  int v2; // r2

  if ( a2 )
    v2 = *result | 1;
  else
    v2 = *result & 0xFFFE;
  *result = v2;
  return result;
}

//----- (08004614) --------------------------------------------------------
signed int sub_8004614()
{
  signed int result; // r0

  MEMORY[0x42220194] = 0;
  MEMORY[0x20000108] = -1;
  MEMORY[0x2000010B] = 72;
  sub_8007E68((int *)0x40011800, (_BYTE *)0x20000108);
  result = 1;
  MEMORY[0x4221019C] = 1;
  MEMORY[0x42220190] = 1;
  return result;
}

//----- (0800463E) --------------------------------------------------------
signed int sub_800463E()
{
  signed int result; // r0

  MEMORY[0x42220194] = 1;
  MEMORY[0x20000108] = -1;
  MEMORY[0x2000010B] = 16;
  MEMORY[0x2000010A] = 3;
  sub_8007E68((int *)0x40011800, (_BYTE *)0x20000108);
  result = 0xFFFF;
  MEMORY[0x4001180C] = 0xFFFF;
  return result;
}

//----- (0800467E) --------------------------------------------------------
signed int sub_800467E()
{
  signed int result; // r0

  result = 1;
  MEMORY[0x422181A8] = 1;
  return result;
}

//----- (08004690) --------------------------------------------------------
int sub_8004690()
{
  return MEMORY[0x40011808];
}

//----- (0800469A) --------------------------------------------------------
int __fastcall sub_800469A(int result)
{
  MEMORY[0x4221019C] = 0;
  MEMORY[0x422181A8] = 1;
  MEMORY[0x4001180C] = result;
  MEMORY[0x42220190] = 1;
  MEMORY[0x42220194] = 1;
  return result;
}

//----- (080046CC) --------------------------------------------------------
int __fastcall sub_80046CC(int result)
{
  MEMORY[0x4221019C] = 1;
  MEMORY[0x422181A8] = 1;
  MEMORY[0x4001180C] = result;
  MEMORY[0x42220190] = 1;
  MEMORY[0x42220194] = 1;
  return result;
}

//----- (080046FE) --------------------------------------------------------
int __fastcall sub_80046FE(int result)
{
  MEMORY[0x4221019C] = 1;
  MEMORY[0x422181A8] = 1;
  MEMORY[0x4001180C] = result;
  MEMORY[0x42220190] = 1;
  MEMORY[0x42220194] = 1;
  return result;
}

//----- (08004A28) --------------------------------------------------------
int __fastcall sub_8004A28(int a1)
{
  int v1; // r3

  sub_800469A(a1);
  return sub_80046FE(v1);
}

//----- (08004AB6) --------------------------------------------------------
int __fastcall sub_8004AB6(int a1, int a2)
{
  int v2; // r4
  int v3; // r3
  unsigned __int8 v4; // r3

  v2 = a2;
  sub_800469A(42);
  sub_80046CC(v2 >> 8);
  sub_80046CC((unsigned __int8)v2);
  sub_80046CC(1);
  sub_80046CC(223);
  sub_800469A(43);
  sub_80046CC(v3 >> 8);
  sub_80046CC(v4);
  sub_80046CC(1);
  return sub_80046CC(63);
}

//----- (08004B66) --------------------------------------------------------
int __fastcall sub_8004B66(int a1, int a2, int a3)
{
  int v3; // r6

  v3 = a3;
  sub_8004AB6(a2, a1);
  sub_800469A(44);
  return sub_80046FE(v3);
}

//----- (08004B84) --------------------------------------------------------
int __fastcall sub_8004B84(int a1, int a2)
{
  int v2; // r4
  int v3; // r3
  unsigned __int8 v4; // r3

  v2 = a2;
  sub_800469A(42);
  sub_80046CC(v2 >> 8);
  sub_80046CC((unsigned __int8)v2);
  sub_80046CC(1);
  sub_80046CC(223);
  sub_800469A(43);
  sub_80046CC(v3 >> 8);
  sub_80046CC(v4);
  sub_80046CC(1);
  sub_80046CC(63);
  sub_800469A(44);
  return sub_80046FE(MEMORY[0x20000104]);
}

//----- (08004BF0) --------------------------------------------------------
int __fastcall sub_8004BF0(int a1, int a2, int a3)
{
  int v3; // r4
  int v4; // r5
  int v5; // r6
  int v6; // r3
  unsigned __int8 v7; // r3

  v3 = a1;
  v4 = a2;
  v5 = a3;
  sub_800469A(42);
  sub_80046CC(v3 >> 8);
  sub_80046CC((unsigned __int8)v3);
  sub_80046CC(v5 >> 8);
  sub_80046CC((unsigned __int8)v5);
  sub_800469A(43);
  sub_80046CC(v4 >> 8);
  sub_80046CC((unsigned __int8)v4);
  sub_80046CC(v6 >> 8);
  return sub_80046CC(v7);
}

//----- (08004C36) --------------------------------------------------------
int __fastcall sub_8004C36(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r5
  int v7; // r6
  int v8; // r7
  int result; // r0
  int i; // r8

  v5 = a1;
  v6 = a2;
  v7 = a3;
  v8 = a4;
  sub_8004BF0(a1, a2, a3);
  sub_800469A(44);
  result = v7 - v5 + 1;
  for ( i = result * (v8 - v6 + 1); i; --i )
    result = sub_80046FE(a5);
  return result;
}

//----- (08004D8A) --------------------------------------------------------
int __fastcall sub_8004D8A(int a1, int a2, int a3, unsigned __int16 a4, unsigned __int16 a5)
{
  int v5; // r4
  unsigned __int16 v6; // r8
  int result; // r0
  unsigned int i; // r5
  int v9; // r3
  unsigned int j; // r9
  int v11; // r3

  v5 = a3;
  v6 = a4;
  sub_8004BF0(a1, a2, (unsigned __int16)(a1 + 7));
  result = sub_800469A(44);
  for ( i = 0; i < 0x10; ++i )
  {
    result = i + 16 * v5;
    LOBYTE(v9) = *(_BYTE *)(result + 134270502);
    for ( j = 0; j < 8; ++j )
    {
      if ( (v9 & 0x80) == 128 )
        sub_80046FE(v6);
      else
        sub_80046FE(a5);
      result = v11 << 25;
      v9 = 2 * v11 & 0xFF;
    }
  }
  return result;
}

//----- (080050B0) --------------------------------------------------------
int __fastcall sub_80050B0(int a1, int a2, int a3, unsigned __int16 a4, unsigned __int16 a5)
{
  return sub_8004D8A(a1, a2, a3, a4, a5);
}

//----- (080050D4) --------------------------------------------------------
int __fastcall sub_80050D4(int a1, int a2)
{
  sub_8004BF0(a1, a2, (unsigned __int16)(a1 + 15));
  return sub_800469A(44);
}

//----- (080054BA) --------------------------------------------------------
int __fastcall sub_80054BA(int a1, int a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r6
  signed __int16 v6; // r7
  signed __int16 v7; // r8
  int v8; // r4
  int i; // r11
  int result; // r0
  unsigned __int16 v11; // [sp+0h] [bp-44h]
  unsigned __int16 v12; // [sp+4h] [bp-40h]
  int v13; // [sp+8h] [bp-3Ch]
  int v14; // [sp+Ch] [bp-38h]

  v14 = 0;
  v13 = 0;
  v4 = a3 - a1;
  v5 = a4 - a2;
  v12 = a1;
  v11 = a2;
  MEMORY[0x20000104] = -1;
  if ( a3 - a1 <= 0 )
  {
    if ( a3 == a1 )
    {
      v6 = 0;
    }
    else
    {
      v6 = -1;
      v4 = a1 - a3;
    }
  }
  else
  {
    v6 = 1;
  }
  if ( v5 <= 0 )
  {
    if ( a4 == a2 )
    {
      v7 = 0;
    }
    else
    {
      v7 = -1;
      v5 = a2 - a4;
    }
  }
  else
  {
    v7 = 1;
  }
  if ( v4 <= v5 )
    v8 = v5;
  else
    v8 = v4;
  for ( i = 0; ; i = (unsigned __int16)(i + 1) )
  {
    result = v8 + 1;
    if ( i > v8 + 1 )
      break;
    sub_8004B84(v12, v11);
    v14 += v4;
    v13 += v5;
    if ( v14 > v8 )
    {
      v14 -= v8;
      v12 += v6;
    }
    if ( v13 > v8 )
    {
      v13 -= v8;
      v11 += v7;
    }
  }
  return result;
}

//----- (08005572) --------------------------------------------------------
signed int __fastcall sub_8005572(int a1, int a2, int a3, int a4, __int16 a5)
{
  int v5; // r11
  int v6; // r5
  int v7; // r6
  signed __int16 v8; // r7
  signed __int16 v9; // r8
  int v10; // r4
  signed int result; // r0
  unsigned __int16 v12; // [sp+0h] [bp-44h]
  unsigned __int16 v13; // [sp+4h] [bp-40h]
  int v14; // [sp+8h] [bp-3Ch]
  int i; // [sp+Ch] [bp-38h]

  v14 = 0;
  v5 = 0;
  v6 = a3 - a1;
  v7 = a4 - a2;
  v13 = a1;
  v12 = a2;
  MEMORY[0x20000104] = a5;
  if ( a3 - a1 <= 0 )
  {
    if ( a3 == a1 )
    {
      v8 = 0;
    }
    else
    {
      v8 = -1;
      v6 = a1 - a3;
    }
  }
  else
  {
    v8 = 1;
  }
  if ( v7 <= 0 )
  {
    if ( a4 == a2 )
    {
      v9 = 0;
    }
    else
    {
      v9 = -1;
      v7 = a2 - a4;
    }
  }
  else
  {
    v9 = 1;
  }
  if ( v6 <= v7 )
    v10 = v7;
  else
    v10 = v6;
  for ( i = 0; i <= v10 + 1; i = (unsigned __int16)(i + 1) )
  {
    sub_8004B84(v13, v12);
    v14 += v6;
    v5 += v7;
    if ( v14 > v10 )
    {
      v14 -= v10;
      v13 += v8;
    }
    if ( v5 > v10 )
    {
      v5 -= v10;
      v12 += v9;
    }
  }
  result = 0xFFFF;
  MEMORY[0x20000104] = -1;
  return result;
}

//----- (08005758) --------------------------------------------------------
int __fastcall sub_8005758(int a1, int a2, char a3, int a4, int a5)
{
  int v5; // r7
  int v6; // r8
  int v7; // r4
  int v8; // r11
  int v9; // r6
  int i; // r5
  int v11; // r9
  int j; // r10
  int result; // r0
  int v14; // [sp+0h] [bp-28h]

  v5 = a1;
  v6 = a2;
  v7 = a4;
  v8 = a2;
  v14 = (unsigned __int8)((a4 / 8 + (a4 % 8 != 0)) * (a4 / 2));
  v9 = (unsigned __int8)(a3 - 32);
  for ( i = 0; ; i = (unsigned __int8)(i + 1) )
  {
    result = v14;
    if ( i >= v14 )
      break;
    switch ( v7 )
    {
      case 12:
        v11 = *((unsigned __int8 *)&word_8009EA6[6 * v9] + i);
        break;
      case 16:
        v11 = *(unsigned __int8 *)(16 * v9 + 134259482 + i);
        break;
      case 24:
        v11 = *(unsigned __int8 *)(36 * v9 + 134261002 + i);
        break;
      case 32:
        v11 = *(unsigned __int8 *)((v9 << 6) + 134264422 + i);
        break;
      default:
        return result;
    }
    for ( j = 0; j < 8; j = (j + 1) & 0xFF )
    {
      if ( v11 & 0x80 )
      {
        sub_8004B66(v5, v6, MEMORY[0x20000104]);
      }
      else if ( !a5 )
      {
        sub_8004B66(v5, v6, MEMORY[0x20000106]);
      }
      v11 = 2 * v11 & 0xFF;
      v6 = (unsigned __int16)(v6 + 1);
      result = MEMORY[0x20000364];
      if ( MEMORY[0x20000364] <= v5 )
        return result;
      if ( v6 - v8 == v7 )
      {
        v6 = v8;
        v5 = (unsigned __int16)(v5 + 1);
        result = MEMORY[0x20000364];
        if ( MEMORY[0x20000364] <= v5 )
          return result;
        break;
      }
    }
  }
  return result;
}
// 8009EA6: using guessed type __int16 word_8009EA6[];

//----- (08005890) --------------------------------------------------------
signed int __fastcall sub_8005890(int a1, int a2)
{
  int v2; // r2
  signed int result; // r0
  bool v4; // zf

  v2 = a1;
  for ( result = 1; ; result *= v2 )
  {
    v4 = a2 == 0;
    a2 = (unsigned __int8)(a2 - 1);
    if ( v4 )
      break;
  }
  return result;
}

//----- (080059CA) --------------------------------------------------------
int __fastcall sub_80059CA(int a1, int a2, char a3, int a4, int a5, int a6)
{
  int v6; // r7
  int v7; // r8
  int v8; // r4
  int v9; // r6
  int i; // r5
  int v11; // r9
  int j; // r11
  int result; // r0
  int v14; // [sp+0h] [bp-2Ch]
  int v15; // [sp+4h] [bp-28h]

  v6 = a1;
  v7 = a2;
  v8 = a4;
  v15 = a2;
  v14 = (unsigned __int8)((a4 / 8 + (a4 % 8 != 0)) * (a4 / 2));
  v9 = (unsigned __int8)(a3 - 32);
  for ( i = 0; ; i = (unsigned __int8)(i + 1) )
  {
    result = v14;
    if ( i >= v14 )
      break;
    switch ( v8 )
    {
      case 12:
        v11 = *((unsigned __int8 *)&word_8009EA6[6 * v9] + i);
        break;
      case 16:
        v11 = *(unsigned __int8 *)(16 * v9 + 134259482 + i);
        break;
      case 24:
        v11 = *(unsigned __int8 *)(36 * v9 + 134261002 + i);
        break;
      case 32:
        v11 = *(unsigned __int8 *)((v9 << 6) + 134264422 + i);
        break;
      default:
        return result;
    }
    for ( j = 0; j < 8; j = (j + 1) & 0xFF )
    {
      if ( a6 )
      {
        if ( v11 & 0x80 )
        {
          sub_8004B66(v6, v7, 2016);
        }
        else if ( !a5 )
        {
          sub_8004B66(v6, v7, MEMORY[0x20000106]);
        }
      }
      else if ( v11 & 0x80 )
      {
        sub_8004B66(v6, v7, MEMORY[0x20000104]);
      }
      else if ( !a5 )
      {
        sub_8004B66(v6, v7, MEMORY[0x20000106]);
      }
      v11 = 2 * v11 & 0xFF;
      v7 = (unsigned __int16)(v7 + 1);
      result = MEMORY[0x20000364];
      if ( MEMORY[0x20000364] <= v6 )
        return result;
      if ( v7 - v15 == v8 )
      {
        v7 = v15;
        v6 = (unsigned __int16)(v6 + 1);
        result = MEMORY[0x20000364];
        if ( MEMORY[0x20000364] <= v6 )
          return result;
        break;
      }
    }
  }
  return result;
}
// 8009EA6: using guessed type __int16 word_8009EA6[];

//----- (08005C1C) --------------------------------------------------------
int __fastcall sub_8005C1C(int a1)
{
  int result; // r0

  MEMORY[0xE000E014] = MEMORY[0x2000010E] * a1;
  MEMORY[0xE000E018] = 0;
  MEMORY[0xE000E010] |= 1u;
  do
    result = MEMORY[0xE000E010];
  while ( MEMORY[0xE000E010] & 1 && !(MEMORY[0xE000E010] & 0x10000) );
  MEMORY[0xE000E010] &= 0xFFFFFFFE;
  MEMORY[0xE000E018] = 0;
  return result;
}

//----- (08005C74) --------------------------------------------------------
int sub_8005C74()
{
  if ( MEMORY[0x2000011A] )
  {
    if ( MEMORY[0x42220134] )
    {
      ++MEMORY[0x20000110];
      if ( (signed int)MEMORY[0x20000110] >= 50 )
      {
        MEMORY[0x20000110] = 0;
        MEMORY[0x2000011A] = 0;
      }
    }
    else
    {
      MEMORY[0x20000110] = 0;
    }
  }
  else if ( MEMORY[0x42220134] )
  {
    MEMORY[0x20000110] = 0;
  }
  else
  {
    ++MEMORY[0x20000110];
    if ( (signed int)MEMORY[0x20000110] >= 50 )
    {
      MEMORY[0x20000110] = 0;
      MEMORY[0x2000011A] = 1;
    }
  }
  return MEMORY[0x2000011A];
}

//----- (08005CD4) --------------------------------------------------------
int sub_8005CD4()
{
  if ( MEMORY[0x2000011B] )
  {
    if ( MEMORY[0x4222013C] )
    {
      ++MEMORY[0x20000111];
      if ( (signed int)MEMORY[0x20000111] >= 50 )
      {
        MEMORY[0x20000111] = 0;
        MEMORY[0x2000011B] = 0;
      }
    }
    else
    {
      MEMORY[0x20000111] = 0;
    }
  }
  else if ( MEMORY[0x4222013C] )
  {
    MEMORY[0x20000111] = 0;
  }
  else
  {
    ++MEMORY[0x20000111];
    if ( (signed int)MEMORY[0x20000111] >= 50 )
    {
      MEMORY[0x20000111] = 0;
      MEMORY[0x2000011B] = 1;
    }
  }
  return MEMORY[0x2000011B];
}

//----- (08005D34) --------------------------------------------------------
int sub_8005D34()
{
  if ( MEMORY[0x2000011C] )
  {
    if ( MEMORY[0x4221012C] )
    {
      ++MEMORY[0x20000112];
      if ( (signed int)MEMORY[0x20000112] >= 50 )
      {
        MEMORY[0x20000112] = 0;
        MEMORY[0x2000011C] = 0;
      }
    }
    else
    {
      MEMORY[0x20000112] = 0;
    }
  }
  else if ( MEMORY[0x4221012C] )
  {
    MEMORY[0x20000112] = 0;
  }
  else
  {
    ++MEMORY[0x20000112];
    if ( (signed int)MEMORY[0x20000112] >= 50 )
    {
      MEMORY[0x20000112] = 0;
      MEMORY[0x2000011C] = 1;
    }
  }
  return MEMORY[0x2000011C];
}

//----- (08005D94) --------------------------------------------------------
int sub_8005D94()
{
  if ( MEMORY[0x2000011D] )
  {
    if ( MEMORY[0x4222011C] )
    {
      ++MEMORY[0x20000113];
      if ( (signed int)MEMORY[0x20000113] >= 50 )
      {
        MEMORY[0x20000113] = 0;
        MEMORY[0x2000011D] = 0;
      }
    }
    else
    {
      MEMORY[0x20000113] = 0;
    }
  }
  else if ( MEMORY[0x4222011C] )
  {
    MEMORY[0x20000113] = 0;
  }
  else
  {
    ++MEMORY[0x20000113];
    if ( (signed int)MEMORY[0x20000113] >= 50 )
    {
      MEMORY[0x20000113] = 0;
      MEMORY[0x2000011D] = 1;
    }
  }
  return MEMORY[0x2000011D];
}

//----- (08005DF4) --------------------------------------------------------
int sub_8005DF4()
{
  if ( MEMORY[0x2000011E] )
  {
    if ( MEMORY[0x42228138] )
    {
      ++MEMORY[0x20000114];
      if ( (signed int)MEMORY[0x20000114] >= 50 )
      {
        MEMORY[0x20000114] = 0;
        MEMORY[0x2000011E] = 0;
      }
    }
    else
    {
      MEMORY[0x20000114] = 0;
    }
  }
  else if ( MEMORY[0x42228138] )
  {
    MEMORY[0x20000114] = 0;
  }
  else
  {
    ++MEMORY[0x20000114];
    if ( (signed int)MEMORY[0x20000114] >= 50 )
    {
      MEMORY[0x20000114] = 0;
      MEMORY[0x2000011E] = 1;
    }
  }
  return MEMORY[0x2000011E];
}

//----- (08005E78) --------------------------------------------------------
int sub_8005E78()
{
  if ( MEMORY[0x2000011F] )
  {
    if ( MEMORY[0x42220138] )
    {
      ++MEMORY[0x20000115];
      if ( (signed int)MEMORY[0x20000115] >= 50 )
      {
        MEMORY[0x20000115] = 0;
        MEMORY[0x2000011F] = 0;
      }
    }
    else
    {
      MEMORY[0x20000115] = 0;
    }
  }
  else if ( MEMORY[0x42220138] )
  {
    MEMORY[0x20000115] = 0;
  }
  else
  {
    ++MEMORY[0x20000115];
    if ( (signed int)MEMORY[0x20000115] >= 50 )
    {
      MEMORY[0x20000115] = 0;
      MEMORY[0x2000011F] = 1;
    }
  }
  return MEMORY[0x2000011F];
}

//----- (08005ED8) --------------------------------------------------------
int sub_8005ED8()
{
  if ( MEMORY[0x20000120] )
  {
    if ( MEMORY[0x4222010C] )
    {
      ++MEMORY[0x20000116];
      if ( (signed int)MEMORY[0x20000116] >= 50 )
      {
        MEMORY[0x20000116] = 0;
        MEMORY[0x20000120] = 0;
      }
    }
    else
    {
      MEMORY[0x20000116] = 0;
    }
  }
  else if ( MEMORY[0x4222010C] )
  {
    MEMORY[0x20000116] = 0;
  }
  else
  {
    ++MEMORY[0x20000116];
    if ( (signed int)MEMORY[0x20000116] >= 50 )
    {
      MEMORY[0x20000116] = 0;
      MEMORY[0x20000120] = 1;
    }
  }
  return MEMORY[0x20000120];
}

//----- (08005F38) --------------------------------------------------------
int sub_8005F38()
{
  if ( MEMORY[0x20000121] )
  {
    if ( MEMORY[0x42220120] )
    {
      ++MEMORY[0x20000117];
      if ( (signed int)MEMORY[0x20000117] >= 50 )
      {
        MEMORY[0x20000117] = 0;
        MEMORY[0x20000121] = 0;
      }
    }
    else
    {
      MEMORY[0x20000117] = 0;
    }
  }
  else if ( MEMORY[0x42220120] )
  {
    MEMORY[0x20000117] = 0;
  }
  else
  {
    ++MEMORY[0x20000117];
    if ( (signed int)MEMORY[0x20000117] >= 50 )
    {
      MEMORY[0x20000117] = 0;
      MEMORY[0x20000121] = 1;
    }
  }
  return MEMORY[0x20000121];
}

//----- (08005F98) --------------------------------------------------------
int sub_8005F98()
{
  if ( MEMORY[0x20000122] )
  {
    if ( MEMORY[0x42220118] )
    {
      ++MEMORY[0x20000118];
      if ( (signed int)MEMORY[0x20000118] >= 50 )
      {
        MEMORY[0x20000118] = 0;
        MEMORY[0x20000122] = 0;
      }
    }
    else
    {
      MEMORY[0x20000118] = 0;
    }
  }
  else if ( MEMORY[0x42220118] )
  {
    MEMORY[0x20000118] = 0;
  }
  else
  {
    ++MEMORY[0x20000118];
    if ( (signed int)MEMORY[0x20000118] >= 50 )
    {
      MEMORY[0x20000118] = 0;
      MEMORY[0x20000122] = 1;
    }
  }
  return MEMORY[0x20000122];
}

//----- (08005FF8) --------------------------------------------------------
int sub_8005FF8()
{
  if ( MEMORY[0x20000123] )
  {
    if ( MEMORY[0x42228134] )
    {
      ++MEMORY[0x20000119];
      if ( (signed int)MEMORY[0x20000119] >= 50 )
      {
        MEMORY[0x20000119] = 0;
        MEMORY[0x20000123] = 0;
      }
    }
    else
    {
      MEMORY[0x20000119] = 0;
    }
  }
  else if ( MEMORY[0x42228134] )
  {
    MEMORY[0x20000119] = 0;
  }
  else
  {
    ++MEMORY[0x20000119];
    if ( (signed int)MEMORY[0x20000119] >= 50 )
    {
      MEMORY[0x20000119] = 0;
      MEMORY[0x20000123] = 1;
    }
  }
  return MEMORY[0x20000123];
}

//----- (080060F4) --------------------------------------------------------
signed int __fastcall sub_80060F4(signed int result)
{
  if ( result >= 1 )
  {
    result = (unsigned __int8)(result - 1);
    switch ( result )
    {
      case 0:
        MEMORY[0x422101BC] = 1;
        break;
      case 1:
        MEMORY[0x422201A8] = 1;
        break;
      case 2:
        MEMORY[0x422101B0] = 1;
        break;
      case 3:
        MEMORY[0x422101A0] = 1;
        break;
      case 4:
        MEMORY[0x422201A4] = 1;
        break;
      default:
        return result;
    }
  }
  return result;
}

//----- (0800613E) --------------------------------------------------------
_DWORD *__fastcall sub_800613E(_DWORD *result)
{
  if ( MEMORY[0x20000124] )
  {
    if ( *result > 0xEA0u )
    {
      MEMORY[0x20000133] = 0;
    }
    else
    {
      ++MEMORY[0x20000133];
      if ( (signed int)MEMORY[0x20000133] >= 30 )
      {
        MEMORY[0x20000133] = 0;
        MEMORY[0x20000124] = 0;
      }
    }
  }
  else if ( *result < 0xEE8u )
  {
    MEMORY[0x20000133] = 0;
  }
  else
  {
    ++MEMORY[0x20000133];
    if ( (signed int)MEMORY[0x20000133] >= 30 )
    {
      MEMORY[0x20000133] = 0;
      MEMORY[0x20000124] = 1;
    }
  }
  if ( MEMORY[0x20000125] )
  {
    if ( result[1] > 0xEA0u )
    {
      MEMORY[0x20000134] = 0;
    }
    else
    {
      ++MEMORY[0x20000134];
      if ( (signed int)MEMORY[0x20000134] >= 30 )
      {
        MEMORY[0x20000134] = 0;
        MEMORY[0x20000125] = 0;
      }
    }
  }
  else if ( result[1] < 0xEE8u )
  {
    MEMORY[0x20000134] = 0;
  }
  else
  {
    ++MEMORY[0x20000134];
    if ( (signed int)MEMORY[0x20000134] >= 30 )
    {
      MEMORY[0x20000134] = 0;
      MEMORY[0x20000125] = 1;
    }
  }
  if ( MEMORY[0x20000126] )
  {
    if ( result[2] > 0xEA0u )
    {
      MEMORY[0x20000135] = 0;
    }
    else
    {
      ++MEMORY[0x20000135];
      if ( (signed int)MEMORY[0x20000135] >= 30 )
      {
        MEMORY[0x20000135] = 0;
        MEMORY[0x20000126] = 0;
      }
    }
  }
  else if ( result[2] < 0xEE8u )
  {
    MEMORY[0x20000135] = 0;
  }
  else
  {
    ++MEMORY[0x20000135];
    if ( (signed int)MEMORY[0x20000135] >= 30 )
    {
      MEMORY[0x20000135] = 0;
      MEMORY[0x20000126] = 1;
    }
  }
  if ( MEMORY[0x20000127] )
  {
    if ( result[3] > 0xEA0u )
    {
      MEMORY[0x20000136] = 0;
    }
    else
    {
      ++MEMORY[0x20000136];
      if ( (signed int)MEMORY[0x20000136] >= 30 )
      {
        MEMORY[0x20000136] = 0;
        MEMORY[0x20000127] = 0;
      }
    }
  }
  else if ( result[3] < 0xEE8u )
  {
    MEMORY[0x20000136] = 0;
  }
  else
  {
    ++MEMORY[0x20000136];
    if ( (signed int)MEMORY[0x20000136] >= 30 )
    {
      MEMORY[0x20000136] = 0;
      MEMORY[0x20000127] = 1;
    }
  }
  if ( MEMORY[0x20000128] )
  {
    if ( result[4] > 0xEA0u )
    {
      MEMORY[0x20000137] = 0;
    }
    else
    {
      ++MEMORY[0x20000137];
      if ( (signed int)MEMORY[0x20000137] >= 30 )
      {
        MEMORY[0x20000137] = 0;
        MEMORY[0x20000128] = 0;
      }
    }
  }
  else if ( result[4] < 0xEE8u )
  {
    MEMORY[0x20000137] = 0;
  }
  else
  {
    ++MEMORY[0x20000137];
    if ( (signed int)MEMORY[0x20000137] >= 30 )
    {
      MEMORY[0x20000137] = 0;
      MEMORY[0x20000128] = 1;
    }
  }
  return result;
}

//----- (08006320) --------------------------------------------------------
_QWORD *__fastcall sub_8006320(_QWORD *result)
{
  if ( MEMORY[0x20000129] )
  {
    if ( (unsigned int)(*result >> 32) < (unsigned int)*result + 30 )
    {
      MEMORY[0x20000138] = 0;
    }
    else
    {
      ++MEMORY[0x20000138];
      if ( (signed int)MEMORY[0x20000138] >= 30 )
      {
        MEMORY[0x20000138] = 0;
        MEMORY[0x20000129] = 0;
      }
    }
  }
  else if ( (unsigned int)(*result >> 32) >= (unsigned int)*result + 30 )
  {
    MEMORY[0x20000138] = 0;
  }
  else
  {
    ++MEMORY[0x20000138];
    if ( (signed int)MEMORY[0x20000138] >= 50 )
    {
      MEMORY[0x20000138] = 0;
      MEMORY[0x20000129] = 1;
    }
  }
  if ( MEMORY[0x2000012A] )
  {
    if ( (unsigned int)(*(_QWORD *)((char *)result + 4) >> 32) < (unsigned int)*(_QWORD *)((char *)result + 4) + 30 )
    {
      MEMORY[0x20000139] = 0;
    }
    else
    {
      ++MEMORY[0x20000139];
      if ( (signed int)MEMORY[0x20000139] >= 30 )
      {
        MEMORY[0x20000139] = 0;
        MEMORY[0x2000012A] = 0;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)((char *)result + 4) >> 32) >= (unsigned int)*(_QWORD *)((char *)result + 4) + 30 )
  {
    MEMORY[0x20000139] = 0;
  }
  else
  {
    ++MEMORY[0x20000139];
    if ( (signed int)MEMORY[0x20000139] >= 50 )
    {
      MEMORY[0x20000139] = 0;
      MEMORY[0x2000012A] = 1;
    }
  }
  if ( MEMORY[0x2000012B] )
  {
    if ( (unsigned int)(result[1] >> 32) < (unsigned int)result[1] + 30 )
    {
      MEMORY[0x2000013A] = 0;
    }
    else
    {
      ++MEMORY[0x2000013A];
      if ( (signed int)MEMORY[0x2000013A] >= 30 )
      {
        MEMORY[0x2000013A] = 0;
        MEMORY[0x2000012B] = 0;
      }
    }
  }
  else if ( (unsigned int)(result[1] >> 32) >= (unsigned int)result[1] + 30 )
  {
    MEMORY[0x2000013A] = 0;
  }
  else
  {
    ++MEMORY[0x2000013A];
    if ( (signed int)MEMORY[0x2000013A] >= 50 )
    {
      MEMORY[0x2000013A] = 0;
      MEMORY[0x2000012B] = 1;
    }
  }
  if ( MEMORY[0x2000012C] )
  {
    if ( (unsigned int)(*(_QWORD *)((char *)result + 12) >> 32) < (unsigned int)*(_QWORD *)((char *)result + 12) + 30 )
    {
      MEMORY[0x2000013B] = 0;
    }
    else
    {
      ++MEMORY[0x2000013B];
      if ( (signed int)MEMORY[0x2000013B] >= 30 )
      {
        MEMORY[0x2000013B] = 0;
        MEMORY[0x2000012C] = 0;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)((char *)result + 12) >> 32) >= (unsigned int)*(_QWORD *)((char *)result + 12)
                                                                    + 30 )
  {
    MEMORY[0x2000013B] = 0;
  }
  else
  {
    ++MEMORY[0x2000013B];
    if ( (signed int)MEMORY[0x2000013B] >= 50 )
    {
      MEMORY[0x2000013B] = 0;
      MEMORY[0x2000012C] = 1;
    }
  }
  return result;
}

//----- (080064AA) --------------------------------------------------------
_DWORD *__fastcall sub_80064AA(_DWORD *result)
{
  if ( MEMORY[0x2000012E] )
  {
    if ( *result >= 0x834u )
    {
      MEMORY[0x2000013D] = 0;
    }
    else
    {
      ++MEMORY[0x2000013D];
      if ( (signed int)MEMORY[0x2000013D] >= 25 )
      {
        MEMORY[0x2000013D] = 0;
        MEMORY[0x2000012E] = 0;
      }
    }
  }
  else if ( *result < 0x8E3u )
  {
    MEMORY[0x2000013D] = 0;
  }
  else
  {
    ++MEMORY[0x2000013D];
    if ( (signed int)MEMORY[0x2000013D] >= 50 )
    {
      MEMORY[0x2000013D] = 0;
      MEMORY[0x2000012E] = 1;
    }
  }
  if ( MEMORY[0x2000012F] )
  {
    if ( result[1] >= 0x834u )
    {
      MEMORY[0x2000013E] = 0;
    }
    else
    {
      ++MEMORY[0x2000013E];
      if ( (signed int)MEMORY[0x2000013E] >= 25 )
      {
        MEMORY[0x2000013E] = 0;
        MEMORY[0x2000012F] = 0;
      }
    }
  }
  else if ( result[1] <= 0x8E3u )
  {
    MEMORY[0x2000013E] = 0;
  }
  else
  {
    ++MEMORY[0x2000013E];
    if ( (signed int)MEMORY[0x2000013E] >= 50 )
    {
      MEMORY[0x2000013E] = 0;
      MEMORY[0x2000012F] = 1;
    }
  }
  if ( MEMORY[0x20000130] )
  {
    if ( result[2] >= 0x834u )
    {
      MEMORY[0x2000013F] = 0;
    }
    else
    {
      ++MEMORY[0x2000013F];
      if ( (signed int)MEMORY[0x2000013F] >= 25 )
      {
        MEMORY[0x2000013F] = 0;
        MEMORY[0x20000130] = 0;
      }
    }
  }
  else if ( result[2] <= 0x8E3u )
  {
    MEMORY[0x2000013F] = 0;
  }
  else
  {
    ++MEMORY[0x2000013F];
    if ( (signed int)MEMORY[0x2000013F] >= 50 )
    {
      MEMORY[0x2000013F] = 0;
      MEMORY[0x20000130] = 1;
    }
  }
  if ( MEMORY[0x20000131] )
  {
    if ( result[4] >= 0x834u )
    {
      MEMORY[0x20000140] = 0;
    }
    else
    {
      ++MEMORY[0x20000140];
      if ( (signed int)MEMORY[0x20000140] >= 25 )
      {
        MEMORY[0x20000140] = 0;
        MEMORY[0x20000131] = 0;
      }
    }
  }
  else if ( result[4] <= 0x8E3u )
  {
    MEMORY[0x20000140] = 0;
  }
  else
  {
    ++MEMORY[0x20000140];
    if ( (signed int)MEMORY[0x20000140] >= 50 )
    {
      MEMORY[0x20000140] = 0;
      MEMORY[0x20000131] = 1;
    }
  }
  if ( MEMORY[0x20000132] )
  {
    if ( result[3] >= 0x834u )
    {
      MEMORY[0x20000141] = 0;
    }
    else
    {
      ++MEMORY[0x20000141];
      if ( (signed int)MEMORY[0x20000141] >= 25 )
      {
        MEMORY[0x20000141] = 0;
        MEMORY[0x20000132] = 0;
      }
    }
  }
  else if ( result[3] <= 0x8E3u )
  {
    MEMORY[0x20000141] = 0;
  }
  else
  {
    ++MEMORY[0x20000141];
    if ( (signed int)MEMORY[0x20000141] >= 50 )
    {
      MEMORY[0x20000141] = 0;
      MEMORY[0x20000132] = 1;
    }
  }
  return result;
}

//----- (08006950) --------------------------------------------------------
signed int __fastcall sub_8006950(signed int result)
{
  if ( result >= 1 )
  {
    result = (unsigned __int8)(result - 1);
    switch ( result )
    {
      case 0:
        MEMORY[0x42218190] = 0;
        break;
      case 1:
        MEMORY[0x42218194] = 0;
        break;
      case 2:
        MEMORY[0x42218198] = 0;
        break;
      case 3:
        MEMORY[0x4221819C] = 0;
        break;
      case 4:
        MEMORY[0x422181A0] = 0;
        break;
      default:
        return result;
    }
  }
  return result;
}

//----- (0800699A) --------------------------------------------------------
signed int __fastcall sub_800699A(signed int result)
{
  if ( result >= 1 )
  {
    result = (unsigned __int8)(result - 1);
    switch ( result )
    {
      case 0:
        MEMORY[0x42218190] = 1;
        break;
      case 1:
        MEMORY[0x42218194] = 1;
        break;
      case 2:
        MEMORY[0x42218198] = 1;
        break;
      case 3:
        MEMORY[0x4221819C] = 1;
        break;
      case 4:
        MEMORY[0x422181A0] = 1;
        break;
      default:
        return result;
    }
  }
  return result;
}

//----- (080069E4) --------------------------------------------------------
_DWORD *__fastcall sub_80069E4(_DWORD *result)
{
  if ( *result >= 0xB60u )
  {
    MEMORY[0x20000148] = 0;
  }
  else
  {
    ++MEMORY[0x20000148];
    if ( (signed int)MEMORY[0x20000148] >= 50 )
    {
      MEMORY[0x20000148] = 0;
      MEMORY[0x2000014D] = 1;
    }
  }
  if ( result[1] >= 0xB60u )
  {
    MEMORY[0x20000149] = 0;
  }
  else
  {
    ++MEMORY[0x20000149];
    if ( (signed int)MEMORY[0x20000149] >= 50 )
    {
      MEMORY[0x20000149] = 0;
      MEMORY[0x2000014E] = 1;
    }
  }
  if ( result[2] >= 0xB60u )
  {
    MEMORY[0x2000014A] = 0;
  }
  else
  {
    ++MEMORY[0x2000014A];
    if ( (signed int)MEMORY[0x2000014A] >= 50 )
    {
      MEMORY[0x2000014A] = 0;
      MEMORY[0x2000014F] = 1;
    }
  }
  if ( result[3] >= 0xB60u )
  {
    MEMORY[0x2000014B] = 0;
  }
  else
  {
    ++MEMORY[0x2000014B];
    if ( (signed int)MEMORY[0x2000014B] >= 50 )
    {
      MEMORY[0x2000014B] = 0;
      MEMORY[0x20000150] = 1;
    }
  }
  if ( result[4] >= 0xB60u )
  {
    MEMORY[0x2000014C] = 0;
  }
  else
  {
    ++MEMORY[0x2000014C];
    if ( (signed int)MEMORY[0x2000014C] >= 50 )
    {
      MEMORY[0x2000014C] = 0;
      MEMORY[0x20000151] = 1;
    }
  }
  return result;
}

//----- (08006AF8) --------------------------------------------------------
int __fastcall sub_8006AF8(int result)
{
  if ( MEMORY[0x20000152] )
  {
    if ( (unsigned int)(*(_QWORD *)result >> 32) < (unsigned int)*(_QWORD *)result + 115 )
    {
      MEMORY[0x20000159] = 0;
    }
    else
    {
      ++MEMORY[0x20000159];
      if ( (signed int)MEMORY[0x20000159] >= 30 )
      {
        MEMORY[0x20000159] = 0;
        MEMORY[0x20000152] = 0;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)result >> 32) >= (unsigned int)*(_QWORD *)result + 115 )
  {
    MEMORY[0x20000159] = 0;
  }
  else
  {
    ++MEMORY[0x20000159];
    if ( (signed int)MEMORY[0x20000159] >= 30 )
    {
      MEMORY[0x20000159] = 0;
      MEMORY[0x20000152] = 1;
    }
  }
  if ( MEMORY[0x20000153] )
  {
    if ( (unsigned int)(*(_QWORD *)(result + 4) >> 32) < (unsigned int)*(_QWORD *)(result + 4) + 115 )
    {
      MEMORY[0x2000015A] = 0;
    }
    else
    {
      ++MEMORY[0x2000015A];
      if ( (signed int)MEMORY[0x2000015A] >= 30 )
      {
        MEMORY[0x2000015A] = 0;
        MEMORY[0x20000153] = 0;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)(result + 4) >> 32) >= (unsigned int)*(_QWORD *)(result + 4) + 115 )
  {
    MEMORY[0x2000015A] = 0;
  }
  else
  {
    ++MEMORY[0x2000015A];
    if ( (signed int)MEMORY[0x2000015A] >= 30 )
    {
      MEMORY[0x2000015A] = 0;
      MEMORY[0x20000153] = 1;
    }
  }
  if ( MEMORY[0x20000154] )
  {
    if ( (unsigned int)(*(_QWORD *)(result + 8) >> 32) < (unsigned int)*(_QWORD *)(result + 8) + 115 )
    {
      MEMORY[0x2000015B] = 0;
    }
    else
    {
      ++MEMORY[0x2000015B];
      if ( (signed int)MEMORY[0x2000015B] >= 30 )
      {
        MEMORY[0x2000015B] = 0;
        MEMORY[0x20000154] = 1;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)(result + 8) >> 32) >= (unsigned int)*(_QWORD *)(result + 8) + 115 )
  {
    MEMORY[0x2000015B] = 0;
  }
  else
  {
    ++MEMORY[0x2000015B];
    if ( (signed int)MEMORY[0x2000015B] >= 30 )
    {
      MEMORY[0x2000015B] = 0;
      MEMORY[0x20000154] = 1;
    }
  }
  if ( MEMORY[0x20000155] )
  {
    if ( (unsigned int)(*(_QWORD *)(result + 12) >> 32) < (unsigned int)*(_QWORD *)(result + 12) + 115 )
    {
      MEMORY[0x2000015C] = 0;
    }
    else
    {
      ++MEMORY[0x2000015C];
      if ( (signed int)MEMORY[0x2000015C] >= 30 )
      {
        MEMORY[0x2000015C] = 0;
        MEMORY[0x20000155] = 0;
      }
    }
  }
  else if ( (unsigned int)(*(_QWORD *)(result + 12) >> 32) >= (unsigned int)*(_QWORD *)(result + 12) + 115 )
  {
    MEMORY[0x2000015C] = 0;
  }
  else
  {
    ++MEMORY[0x2000015C];
    if ( (signed int)MEMORY[0x2000015C] >= 30 )
    {
      MEMORY[0x2000015C] = 0;
      MEMORY[0x20000155] = 1;
    }
  }
  if ( MEMORY[0x20000156] )
  {
    if ( *(_DWORD *)(result + 16) < (unsigned int)(*(_DWORD *)result + 200) )
    {
      MEMORY[0x2000015D] = 0;
    }
    else
    {
      ++MEMORY[0x2000015D];
      if ( (signed int)MEMORY[0x2000015D] >= 30 )
      {
        MEMORY[0x2000015D] = 0;
        MEMORY[0x20000156] = 1;
      }
    }
  }
  else if ( *(_DWORD *)(result + 16) >= (unsigned int)(*(_DWORD *)result + 200) )
  {
    MEMORY[0x2000015D] = 0;
  }
  else
  {
    ++MEMORY[0x2000015D];
    if ( (signed int)MEMORY[0x2000015D] >= 30 )
    {
      MEMORY[0x2000015D] = 0;
      MEMORY[0x20000156] = 1;
    }
  }
  if ( MEMORY[0x20000157] )
  {
    if ( *(_DWORD *)(result + 16) < (unsigned int)(*(_DWORD *)(result + 4) + 200) )
    {
      MEMORY[0x2000015E] = 0;
    }
    else
    {
      ++MEMORY[0x2000015E];
      if ( (signed int)MEMORY[0x2000015E] >= 30 )
      {
        MEMORY[0x2000015E] = 0;
        MEMORY[0x20000157] = 0;
      }
    }
  }
  else if ( *(_DWORD *)(result + 16) >= (unsigned int)(*(_DWORD *)(result + 4) + 200) )
  {
    MEMORY[0x2000015E] = 0;
  }
  else
  {
    ++MEMORY[0x2000015E];
    if ( (signed int)MEMORY[0x2000015E] >= 30 )
    {
      MEMORY[0x2000015E] = 0;
      MEMORY[0x20000157] = 1;
    }
  }
  if ( MEMORY[0x20000158] )
  {
    if ( *(_DWORD *)(result + 12) < (unsigned int)(*(_DWORD *)result + 170) )
    {
      MEMORY[0x2000015F] = 0;
    }
    else
    {
      ++MEMORY[0x2000015F];
      if ( (signed int)MEMORY[0x2000015F] >= 30 )
      {
        MEMORY[0x2000015F] = 0;
        MEMORY[0x20000158] = 0;
      }
    }
  }
  else if ( *(_DWORD *)(result + 12) >= (unsigned int)(*(_DWORD *)result + 170) )
  {
    MEMORY[0x2000015F] = 0;
  }
  else
  {
    ++MEMORY[0x2000015F];
    if ( (signed int)MEMORY[0x2000015F] >= 30 )
    {
      MEMORY[0x2000015F] = 0;
      MEMORY[0x20000158] = 1;
    }
  }
  return result;
}

//----- (080075B4) --------------------------------------------------------
signed int sub_80075B4()
{
  signed int result; // r0

  MEMORY[0x40021000] |= 1u;
  MEMORY[0x40021004] &= 0xF8FF0000;
  MEMORY[0x40021000] &= 0xFEF6FFFF;
  MEMORY[0x40021000] &= 0xFFFBFFFF;
  MEMORY[0x40021004] &= 0xFF80FFFF;
  result = 10420224;
  MEMORY[0x40021008] = 10420224;
  return result;
}

//----- (080075F4) --------------------------------------------------------
int __fastcall sub_80075F4(int result)
{
  MEMORY[0x40021000] &= 0xFFFEFFFF;
  MEMORY[0x40021000] &= 0xFFFBFFFF;
  if ( result == 0x10000 )
  {
    MEMORY[0x40021000] |= 0x10000u;
  }
  else if ( result == 0x40000 )
  {
    MEMORY[0x40021000] |= 0x50000u;
  }
  return result;
}

//----- (0800763A) --------------------------------------------------------
BOOL __fastcall sub_800763A(int a1)
{
  int v1; // r3

  if ( a1 >> 5 == 1 )
  {
    v1 = MEMORY[0x40021000];
  }
  else if ( a1 >> 5 == 2 )
  {
    v1 = MEMORY[0x40021020];
  }
  else
  {
    v1 = MEMORY[0x40021024];
  }
  return ((1 << (a1 & 0x1F)) & v1) != 0;
}

//----- (08007672) --------------------------------------------------------
BOOL sub_8007672()
{
  BOOL v0; // r5
  int v2; // [sp+0h] [bp-10h]

  v2 = 0;
  do
  {
    v0 = sub_800763A(49);
    ++v2;
  }
  while ( v2 != 1280 && !v0 );
  return sub_800763A(49) != 0;
}

//----- (080076C4) --------------------------------------------------------
unsigned int __fastcall sub_80076C4(int a1, int a2)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFC0FFFF | a1 | a2;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (080076DC) --------------------------------------------------------
int __fastcall sub_80076DC(int result)
{
  MEMORY[0x42420060] = result;
  return result;
}

//----- (080076E2) --------------------------------------------------------
unsigned int __fastcall sub_80076E2(int a1)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFFFFFFC | a1;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (080076F4) --------------------------------------------------------
int sub_80076F4()
{
  return MEMORY[0x40021004] & 0xC;
}

//----- (080076FE) --------------------------------------------------------
unsigned int __fastcall sub_80076FE(int a1)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFFFFF0F | a1;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (08007710) --------------------------------------------------------
unsigned int __fastcall sub_8007710(int a1)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFFFF8FF | a1;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (08007722) --------------------------------------------------------
unsigned int __fastcall sub_8007722(int a1)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFFFC7FF | 8 * a1;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (08007756) --------------------------------------------------------
unsigned int __fastcall sub_8007756(int a1)
{
  unsigned int result; // r0

  result = MEMORY[0x40021004] & 0xFFFF3FFF | a1;
  MEMORY[0x40021004] = result;
  return result;
}

//----- (08007768) --------------------------------------------------------
int __fastcall sub_8007768(int result)
{
  MEMORY[0x40021020] = 0;
  if ( result == 1 )
  {
    MEMORY[0x40021020] = 1;
  }
  else if ( result == 4 )
  {
    MEMORY[0x40021020] = 5;
  }
  return result;
}

//----- (08007794) --------------------------------------------------------
int __fastcall sub_8007794(int result)
{
  MEMORY[0x42420480] = result;
  return result;
}

//----- (0800779A) --------------------------------------------------------
int __fastcall sub_800779A(int result)
{
  MEMORY[0x40021020] |= result;
  return result;
}

//----- (080077A6) --------------------------------------------------------
int __fastcall sub_80077A6(int result)
{
  MEMORY[0x4242043C] = result;
  return result;
}

//----- (080077AE) --------------------------------------------------------
_DWORD *__fastcall sub_80077AE(_DWORD *result)
{
  int v1; // r1
  unsigned int v2; // r2

  v1 = MEMORY[0x40021004] & 0xC;
  if ( MEMORY[0x40021004] & 0xC )
  {
    if ( v1 == 4 )
    {
      *result = 8000000;
    }
    else if ( v1 == 8 )
    {
      v2 = ((MEMORY[0x40021004] & 0x3C0000u) >> 18) + 2;
      if ( MEMORY[0x40021004] & 0x10000 )
      {
        if ( MEMORY[0x40021004] & 0x20000 )
          *result = 4000000 * v2;
        else
          *result = 8000000 * v2;
      }
      else
      {
        *result = 4000000 * v2;
      }
    }
    else
    {
      *result = 8000000;
    }
  }
  else
  {
    *result = 8000000;
  }
  result[1] = *result >> *(_BYTE *)(((MEMORY[0x40021004] & 0xF0u) >> 4) + 0x2000016E);
  result[2] = result[1] >> *(_BYTE *)(((MEMORY[0x40021004] & 0x700u) >> 8) + 0x2000016E);
  result[3] = result[1] >> *(_BYTE *)(((MEMORY[0x40021004] & 0x3800u) >> 11) + 0x2000016E);
  result[4] = result[3] / (unsigned int)*(unsigned __int8 *)(((MEMORY[0x40021004] & 0xC000u) >> 14) + 0x2000017E);
  return result;
}

//----- (0800786E) --------------------------------------------------------
int __fastcall sub_800786E(int result, int a2)
{
  if ( a2 )
    MEMORY[0x40021014] |= result;
  else
    MEMORY[0x40021014] &= ~result;
  return result;
}

//----- (08007888) --------------------------------------------------------
int __fastcall sub_8007888(int result, int a2)
{
  if ( a2 )
    MEMORY[0x40021018] |= result;
  else
    MEMORY[0x40021018] &= ~result;
  return result;
}

//----- (080078A2) --------------------------------------------------------
int __fastcall sub_80078A2(int result, int a2)
{
  if ( a2 )
    MEMORY[0x4002101C] |= result;
  else
    MEMORY[0x4002101C] &= ~result;
  return result;
}

//----- (080078BC) --------------------------------------------------------
int __fastcall sub_80078BC(int result, int a2)
{
  if ( a2 )
    MEMORY[0x4002100C] |= result;
  else
    MEMORY[0x4002100C] &= ~result;
  return result;
}

//----- (080078D6) --------------------------------------------------------
int __fastcall sub_80078D6(int result, int a2)
{
  if ( a2 )
    MEMORY[0x40021010] |= result;
  else
    MEMORY[0x40021010] &= ~result;
  return result;
}

//----- (080078F0) --------------------------------------------------------
int __fastcall sub_80078F0(int result)
{
  MEMORY[0x42420440] = result;
  return result;
}

//----- (08007958) --------------------------------------------------------
int __fastcall sub_8007958(int a1)
{
  int v1; // r4
  int result; // r0

  v1 = a1;
  if ( a1 == 1073816576 )
  {
    sub_80078BC(512, 1);
    result = sub_80078BC(512, 0);
  }
  else if ( a1 == 1073817600 )
  {
    sub_80078BC(1024, 1);
    result = sub_80078BC(1024, 0);
  }
  else
  {
    result = 1073822720;
    if ( v1 == 1073822720 )
    {
      sub_80078BC(0x8000, 1);
      result = sub_80078BC(0x8000, 0);
    }
  }
  return result;
}

//----- (080079A6) --------------------------------------------------------
unsigned int __fastcall sub_80079A6(_DWORD *a1, int a2)
{
  _DWORD *v2; // r2
  unsigned int result; // r0

  v2 = a1;
  a1[1] = a1[1] & 0xFFF0FEFF | *(_DWORD *)a2 | (*(unsigned __int8 *)(a2 + 4) << 8);
  a1[2] = a1[2] & 0xFFF1F7FD | (*(_QWORD *)(a2 + 8) >> 32) | *(_QWORD *)(a2 + 8) | 2 * *(unsigned __int8 *)(a2 + 5);
  result = a1[11] & 0xFF0FFFFF | ((unsigned __int8)(*(_BYTE *)(a2 + 16) - 1) << 20);
  v2[11] = result;
  return result;
}

//----- (080079FE) --------------------------------------------------------
int __fastcall sub_80079FE(int result, int a2)
{
  unsigned int v2; // r2

  if ( a2 )
    v2 = *(_DWORD *)(result + 8) | 1;
  else
    v2 = *(_DWORD *)(result + 8) & 0xFFFFFFFE;
  *(_DWORD *)(result + 8) = v2;
  return result;
}

//----- (08007A14) --------------------------------------------------------
int __fastcall sub_8007A14(int result, int a2)
{
  unsigned int v2; // r2

  if ( a2 )
    v2 = *(_DWORD *)(result + 8) | 0x100;
  else
    v2 = *(_DWORD *)(result + 8) & 0xFFFFFEFF;
  *(_DWORD *)(result + 8) = v2;
  return result;
}

//----- (08007A42) --------------------------------------------------------
int __fastcall sub_8007A42(int result)
{
  *(_DWORD *)(result + 8) |= 8u;
  return result;
}

//----- (08007A4C) --------------------------------------------------------
BOOL __fastcall sub_8007A4C(int a1)
{
  return (*(_DWORD *)(a1 + 8) & 8) != 0;
}

//----- (08007A60) --------------------------------------------------------
int __fastcall sub_8007A60(int result)
{
  *(_DWORD *)(result + 8) |= 4u;
  return result;
}

//----- (08007A6A) --------------------------------------------------------
BOOL __fastcall sub_8007A6A(int a1)
{
  return (*(_DWORD *)(a1 + 8) & 4) != 0;
}

//----- (08007A7E) --------------------------------------------------------
int __fastcall sub_8007A7E(int result, int a2)
{
  unsigned int v2; // r2

  if ( a2 )
    v2 = *(_DWORD *)(result + 8) | 0x500000;
  else
    v2 = *(_DWORD *)(result + 8) & 0xFFAFFFFF;
  *(_DWORD *)(result + 8) = v2;
  return result;
}

//----- (08007AD6) --------------------------------------------------------
int __fastcall sub_8007AD6(_DWORD *a1, signed int a2, signed int a3, int a4)
{
  _DWORD *v4; // r4
  int result; // r0

  v4 = a1;
  if ( a2 <= 9 )
    a1[4] = a1[4] & ~(7 << 3 * a2) | (a4 << 3 * a2);
  else
    a1[3] = a1[3] & ~(7 << 3 * (a2 - 10)) | (a4 << 3 * (a2 - 10));
  if ( a3 >= 7 )
  {
    if ( a3 >= 13 )
    {
      result = a1[11] & ~(31 << 5 * (a3 - 13)) | (a2 << 5 * (a3 - 13));
      v4[11] = result;
    }
    else
    {
      result = a1[12] & ~(31 << 5 * (a3 - 7)) | (a2 << 5 * (a3 - 7));
      v4[12] = result;
    }
  }
  else
  {
    result = a1[13] & ~(31 << 5 * (a3 - 1)) | (a2 << 5 * (a3 - 1));
    v4[13] = result;
  }
  return result;
}

//----- (08007BA4) --------------------------------------------------------
int __fastcall sub_8007BA4(int a1)
{
  return (unsigned __int16)*(_DWORD *)(a1 + 76);
}

//----- (08007D60) --------------------------------------------------------
BOOL __fastcall sub_8007D60(_DWORD *a1, int a2)
{
  return (*a1 & a2) != 0;
}

//----- (08007E68) --------------------------------------------------------
unsigned int __fastcall sub_8007E68(int *a1, _BYTE *a2)
{
  int *v2; // r2
  unsigned int result; // r0
  int v4; // r5
  int v5; // r4
  int v6; // r4

  v2 = a1;
  result = 0;
  v4 = a2[3] & 0xF;
  if ( a2[3] & 0x10 )
    v4 |= (unsigned __int8)a2[2];
  if ( *a2 )
  {
    v5 = *v2;
    for ( result = 0; result < 8; ++result )
    {
      if ( (*(unsigned __int16 *)a2 & (1 << result)) == 1 << result )
      {
        v5 = (v4 << 4 * result) | v5 & ~(15 << 4 * result);
        if ( a2[3] == 40 )
        {
          v2[5] = 1 << result;
        }
        else if ( a2[3] == 72 )
        {
          v2[4] = 1 << result;
        }
      }
    }
    *v2 = v5;
  }
  if ( (signed int)*(unsigned __int16 *)a2 > 255 )
  {
    v6 = v2[1];
    for ( result = 0; result < 8; ++result )
    {
      if ( (*(unsigned __int16 *)a2 & (1 << (result + 8))) == 1 << (result + 8) )
      {
        v6 = (v4 << 4 * result) | v6 & ~(15 << 4 * result);
        if ( a2[3] == 40 )
          v2[5] = 1 << (result + 8);
        if ( a2[3] == 72 )
          v2[4] = 1 << (result + 8);
      }
    }
    v2[1] = v6;
  }
  return result;
}

//----- (08008006) --------------------------------------------------------
unsigned int __fastcall sub_8008006(unsigned int result, int a2)
{
  int v2; // r2
  int v3; // r1
  unsigned int v4; // r1

  v2 = a2;
  if ( (result & 0x80000000) == 0x80000000 )
    v3 = MEMORY[0x4001001C];
  else
    v3 = MEMORY[0x40010004];
  if ( (result & 0x300000) == 3145728 )
  {
    v4 = v3 & 0xF0FFFFFF;
    MEMORY[0x40010004] &= 0xF0FFFFFF;
  }
  else if ( (result & 0x100000) == 0x100000 )
  {
    v4 = v3 & ~(3 << (BYTE2(result) & 0xF)) | 0xF000000;
  }
  else
  {
    v4 = v3 & ~((unsigned __int16)result << 16 * (result >> 21)) | 0xF000000;
  }
  if ( v2 )
    v4 |= (unsigned __int16)result << 16 * (result >> 21);
  if ( (result & 0x80000000) == 0x80000000 )
    MEMORY[0x4001001C] = v4;
  else
    MEMORY[0x40010004] = v4;
  return result;
}

//----- (08008090) --------------------------------------------------------
int __fastcall sub_8008090(int result, int a2)
{
  *(_DWORD *)(4 * (a2 >> 2) + 0x40010008) &= ~(15 << (4 * a2 & 0xF));
  *(_DWORD *)(4 * (a2 >> 2) + 0x40010008) |= result << (4 * a2 & 0xF);
  return result;
}

//----- (08008100) --------------------------------------------------------
int __fastcall sub_8008100(int a1)
{
  int v1; // r4
  int result; // r0

  v1 = a1;
  switch ( a1 )
  {
    case 1073818624:
      sub_80078BC(2048, 1);
      result = sub_80078BC(2048, 0);
      break;
    case 1073741824:
      sub_80078D6(1, 1);
      result = sub_80078D6(1, 0);
      break;
    case 1073742848:
      sub_80078D6(2, 1);
      result = sub_80078D6(2, 0);
      break;
    case 1073743872:
      sub_80078D6(4, 1);
      result = sub_80078D6(4, 0);
      break;
    case 1073744896:
      sub_80078D6(8, 1);
      result = sub_80078D6(8, 0);
      break;
    case 1073745920:
      sub_80078D6(16, 1);
      result = sub_80078D6(16, 0);
      break;
    case 1073746944:
      sub_80078D6(32, 1);
      result = sub_80078D6(32, 0);
      break;
    case 1073820672:
      sub_80078BC(0x2000, 1);
      result = sub_80078BC(0x2000, 0);
      break;
    case 1073826816:
      sub_80078BC(0x80000, 1);
      result = sub_80078BC(0x80000, 0);
      break;
    case 1073827840:
      sub_80078BC(0x100000, 1);
      result = sub_80078BC(0x100000, 0);
      break;
    case 1073828864:
      sub_80078BC(0x200000, 1);
      result = sub_80078BC(0x200000, 0);
      break;
    case 1073747968:
      sub_80078D6(64, 1);
      result = sub_80078D6(64, 0);
      break;
    case 1073748992:
      sub_80078D6(128, 1);
      result = sub_80078D6(128, 0);
      break;
    case 1073750016:
      sub_80078D6(256, 1);
      result = sub_80078D6(256, 0);
      break;
    case 1073823744:
      sub_80078BC(0x10000, 1);
      result = sub_80078BC(0x10000, 0);
      break;
    case 1073824768:
      sub_80078BC(0x20000, 1);
      result = sub_80078BC(0x20000, 0);
      break;
    default:
      result = 1073825792;
      if ( v1 == 1073825792 )
      {
        sub_80078BC(0x40000, 1);
        result = sub_80078BC(0x40000, 0);
      }
      break;
  }
  return result;
}

//----- (080082A8) --------------------------------------------------------
__int16 *__fastcall sub_80082A8(__int16 *result, int a2)
{
  __int16 v2; // r2

  v2 = *result;
  if ( result == (__int16 *)1073818624
    || result == (__int16 *)1073820672
    || result == (__int16 *)0x40000000
    || result == (__int16 *)1073742848
    || result == (__int16 *)1073743872
    || result == (__int16 *)1073744896 )
  {
    v2 = v2 & 0xFF8F | *(_WORD *)(a2 + 2);
  }
  if ( result != (__int16 *)1073745920 && result != (__int16 *)1073746944 )
    v2 = v2 & 0xFCFF | *(_WORD *)(a2 + 6);
  *result = v2;
  result[22] = *(_WORD *)(a2 + 4);
  result[20] = *(_WORD *)a2;
  if ( result == (__int16 *)1073818624
    || result == (__int16 *)1073820672
    || result == (__int16 *)1073823744
    || result == (__int16 *)1073824768
    || result == (__int16 *)1073825792 )
  {
    result[24] = *(unsigned __int8 *)(a2 + 8);
  }
  result[10] = 1;
  return result;
}

//----- (0800858C) --------------------------------------------------------
int __fastcall sub_800858C(int result, __int16 a2)
{
  *(_WORD *)(result + 28) &= 0xF3FFu;
  *(_WORD *)(result + 28) |= a2 << 8;
  return result;
}

//----- (080085A6) --------------------------------------------------------
int __fastcall sub_80085A6(int result, int a2, int a3, int a4)
{
  int v4; // r4
  __int16 v5; // r1
  int v6; // r2
  int v7; // r1

  v4 = a2;
  *(_WORD *)(result + 32) &= 0xEFFFu;
  v5 = *(_WORD *)(result + 32);
  v6 = *(_WORD *)(result + 28) & 0xCFF | (a3 << 8) & 0xFFFF | (a4 << 12) & 0xFFFF;
  if ( result != 1073818624
    && result != 1073820672
    && result != 0x40000000
    && result != 1073742848
    && result != 1073743872
    && result != 1073744896 )
  {
    v7 = v5 & 0x7DFF | v4 | 0x1000;
  }
  else
  {
    v7 = (unsigned __int16)(v5 & 0xDFFF) | (v4 << 12) & 0xFFFF | 0x1000;
  }
  *(_WORD *)(result + 28) = v6;
  *(_WORD *)(result + 32) = v7;
  return result;
}

//----- (08008628) --------------------------------------------------------
int __fastcall sub_8008628(int result, __int16 a2)
{
  *(_WORD *)(result + 28) &= 0xFFF3u;
  *(_WORD *)(result + 28) |= a2;
  return result;
}

//----- (0800863A) --------------------------------------------------------
int __fastcall sub_800863A(int result, int a2, int a3, int a4)
{
  int v4; // r4
  __int16 v5; // r1
  int v6; // r2
  int v7; // r1

  v4 = a2;
  *(_WORD *)(result + 32) &= 0xFEFFu;
  v5 = *(_WORD *)(result + 32);
  v6 = (unsigned __int16)(*(_WORD *)(result + 28) & 0xFF0C) | 16 * a4 & 0xFFFF | a3;
  if ( result != 1073818624
    && result != 1073820672
    && result != 0x40000000
    && result != 1073742848
    && result != 1073743872
    && result != 1073744896 )
  {
    v7 = (unsigned __int16)(v5 & 0xF5FF) | v4 | 0x100;
  }
  else
  {
    v7 = (unsigned __int16)(v5 & 0xFDFF) | (v4 << 8) & 0xFFFF | 0x100;
  }
  *(_WORD *)(result + 28) = v6;
  *(_WORD *)(result + 32) = v7;
  return result;
}

//----- (080086B4) --------------------------------------------------------
int __fastcall sub_80086B4(int result, __int16 a2)
{
  *(_WORD *)(result + 24) &= 0xF3FFu;
  *(_WORD *)(result + 24) |= a2 << 8;
  return result;
}

//----- (080086CE) --------------------------------------------------------
int __fastcall sub_80086CE(int result, int a2, int a3, int a4)
{
  int v4; // r4
  __int16 v5; // r1
  int v6; // r2
  int v7; // r1

  v4 = a2;
  *(_WORD *)(result + 32) &= 0xFFEFu;
  v5 = *(_WORD *)(result + 32);
  v6 = *(_WORD *)(result + 24) & 0xCFF | (a4 << 12) & 0xFFFF | (a3 << 8) & 0xFFFF;
  if ( result != 1073818624
    && result != 1073820672
    && result != 0x40000000
    && result != 1073742848
    && result != 1073743872
    && result != 1073744896 )
  {
    v7 = (unsigned __int16)(v5 & 0xFF5F) | v4 | 0x10;
  }
  else
  {
    v7 = (unsigned __int16)(v5 & 0xFFDF) | 16 * v4 & 0xFFFF | 0x10;
  }
  *(_WORD *)(result + 24) = v6;
  *(_WORD *)(result + 32) = v7;
  return result;
}

//----- (08008750) --------------------------------------------------------
int __fastcall sub_8008750(int result, __int16 a2)
{
  *(_WORD *)(result + 24) &= 0xFFF3u;
  *(_WORD *)(result + 24) |= a2;
  return result;
}

//----- (08008762) --------------------------------------------------------
int __fastcall sub_8008762(int result, int a2, int a3, int a4)
{
  int v4; // r4
  __int16 v5; // r1
  int v6; // r2
  int v7; // r1

  v4 = a2;
  *(_WORD *)(result + 32) &= 0xFFFEu;
  v5 = *(_WORD *)(result + 32);
  v6 = (unsigned __int16)(*(_WORD *)(result + 24) & 0xFF0C) | 16 * a4 & 0xFFFF | a3;
  if ( result != 1073818624
    && result != 1073820672
    && result != 0x40000000
    && result != 1073742848
    && result != 1073743872
    && result != 1073744896 )
  {
    v7 = (unsigned __int16)(v5 & 0xFFF5) | v4 | 1;
  }
  else
  {
    v7 = (unsigned __int16)(v5 & 0xFFFD) | v4 | 1;
  }
  *(_WORD *)(result + 24) = v6;
  *(_WORD *)(result + 32) = v7;
  return result;
}

//----- (08008960) --------------------------------------------------------
_WORD *__fastcall sub_8008960(_WORD *result, int a2)
{
  __int16 v2; // r2

  if ( a2 )
    v2 = *result | 1;
  else
    v2 = *result & 0xFFFE;
  *result = v2;
  return result;
}

//----- (08008996) --------------------------------------------------------
int __fastcall sub_8008996(int result, int a2, int a3)
{
  int v3; // r3

  if ( a3 )
    LOWORD(v3) = *(_WORD *)(result + 12) | a2;
  else
    v3 = *(unsigned __int16 *)(result + 12) & ~a2;
  *(_WORD *)(result + 12) = v3;
  return result;
}

//----- (080089C8) --------------------------------------------------------
int __fastcall sub_80089C8(int result)
{
  *(_WORD *)(result + 8) &= 0xFFF8u;
  return result;
}

//----- (080089D4) --------------------------------------------------------
int __fastcall sub_80089D4(int result, __int16 a2)
{
  *(_WORD *)(result + 8) = *(_WORD *)(result + 8) & 0xFF8F | a2;
  return result;
}

//----- (08008A3C) --------------------------------------------------------
int __fastcall sub_8008A3C(int result, __int16 a2, __int16 a3, __int16 a4)
{
  *(_WORD *)(result + 8) = (unsigned __int8)*(_WORD *)(result + 8) | (a4 << 8) | a3 | a2;
  return result;
}

//----- (08008B60) --------------------------------------------------------
_WORD *__fastcall sub_8008B60(_WORD *result, int a2)
{
  __int16 v2; // r2

  if ( a2 )
    v2 = *result | 0x80;
  else
    v2 = *result & 0xFF7F;
  *result = v2;
  return result;
}

//----- (08008EEC) --------------------------------------------------------
int __fastcall sub_8008EEC(int result, __int16 a2)
{
  *(_WORD *)(result + 16) = ~a2;
  return result;
}

//----- (08008F38) --------------------------------------------------------
int __fastcall sub_8008F38(int result)
{
  if ( *(_BYTE *)(result + 6) )
  {
    MEMORY[0x40010400] &= ~*(_DWORD *)result;
    MEMORY[0x40010404] &= ~*(_DWORD *)result;
    *(_DWORD *)(*(unsigned __int8 *)(result + 4) + 0x40010400) |= *(_DWORD *)result;
    MEMORY[0x40010408] &= ~*(_DWORD *)result;
    MEMORY[0x4001040C] &= ~*(_DWORD *)result;
    if ( *(_BYTE *)(result + 5) == 16 )
    {
      MEMORY[0x40010408] |= *(_DWORD *)result;
      MEMORY[0x4001040C] |= *(_DWORD *)result;
    }
    else
    {
      *(_DWORD *)(*(unsigned __int8 *)(result + 5) + 0x40010400) |= *(_DWORD *)result;
    }
  }
  else
  {
    *(_DWORD *)(*(unsigned __int8 *)(result + 4) + 0x40010400) &= ~*(_DWORD *)result;
  }
  return result;
}

//----- (08009004) --------------------------------------------------------
BOOL __fastcall sub_8009004(int a1)
{
  return MEMORY[0x40010414] & a1 && MEMORY[0x40010400] & a1;
}

//----- (08009026) --------------------------------------------------------
int __fastcall sub_8009026(int result)
{
  MEMORY[0x40010414] = result;
  return result;
}

//----- (08009038) --------------------------------------------------------
int sub_8009038()
{
  sub_80078F0(1);
  return sub_80078F0(0);
}

//----- (080090FC) --------------------------------------------------------
int __fastcall sub_80090FC(int a1)
{
  int result; // r0

  result = MEMORY[0x40022000] & 0x38 | a1;
  MEMORY[0x40022000] = result;
  return result;
}

//----- (08009124) --------------------------------------------------------
int __fastcall sub_8009124(int result)
{
  MEMORY[0x40022000] &= 0xFFFFFFEF;
  MEMORY[0x40022000] |= result;
  return result;
}

//----- (0800916E) --------------------------------------------------------
signed int sub_800916E()
{
  if ( MEMORY[0x4002200C] & 1 )
    return 1;
  if ( MEMORY[0x4002200C] & 4 )
    return 2;
  if ( MEMORY[0x4002200C] & 0x10 )
    return 3;
  return 4;
}

//----- (0800919E) --------------------------------------------------------
signed int sub_800919E()
{
  int v0; // r2
  signed int v1; // r3
  int v2; // r2

  v1 = sub_800916E();
  while ( v1 == 1 && v0 )
  {
    v1 = sub_800916E();
    v0 = v2 - 1;
  }
  if ( !v0 )
    v1 = 5;
  return v1;
}

//----- (08009250) --------------------------------------------------------
signed int sub_8009250()
{
  int v0; // r2
  signed int v1; // r3
  int v2; // r2

  v1 = sub_800916E();
  while ( v1 == 1 && v0 )
  {
    v1 = sub_800916E();
    v0 = v2 - 1;
  }
  if ( !v0 )
    v1 = 5;
  return v1;
}

//----- (080092BA) --------------------------------------------------------
BOOL sub_80092BA()
{
  return (MEMORY[0x4002201C] & 2) != 0;
}

//----- (080096B8) --------------------------------------------------------
int __fastcall sub_80096B8(int result)
{
  MEMORY[0xE000ED0C] = result | 0x5FA0000;
  return result;
}

//----- (080096C2) --------------------------------------------------------
unsigned __int8 *__fastcall sub_80096C2(unsigned __int8 *result)
{
  if ( result[3] )
  {
    *(_BYTE *)(*result - 536812544) = 16
                                    * ((result[1] << (4 - ((unsigned __int16)(1792 - (MEMORY[0xE000ED0C] & 0x700)) >> 8))) | result[2] & (0xFu >> ((unsigned __int16)(1792 - (MEMORY[0xE000ED0C] & 0x700)) >> 8)));
    *(_DWORD *)(4 * ((signed int)*result >> 5) - 536813312) = 1 << (*result & 0x1F);
  }
  else
  {
    *(_DWORD *)(4 * ((signed int)*result >> 5) - 536813184) = 1 << (*result & 0x1F);
  }
  return result;
}

//----- (08009758) --------------------------------------------------------
int __fastcall sub_8009758(int result)
{
  if ( result == 4 )
    MEMORY[0xE000E010] |= 4u;
  else
    MEMORY[0xE000E010] &= 0xFFFFFFFB;
  return result;
}

//----- (0800981A) --------------------------------------------------------
unsigned int __fastcall sub_800981A(_WORD *a1, _WORD *a2)
{
  _WORD *v2; // r5
  _WORD *v3; // r6
  int v4; // r0
  int v5; // r10
  unsigned int v6; // r8
  unsigned int v7; // r9
  unsigned int result; // r0
  char v9; // [sp+4h] [bp-34h]
  int v10; // [sp+Ch] [bp-2Ch]
  int v11; // [sp+10h] [bp-28h]

  v2 = a1;
  v3 = a2;
  v4 = (unsigned __int16)a2[6];
  v2[8] = v2[8] & 0xCFFF | a2[3];
  v2[6] = v2[6] & 0xE9F3 | v3[2] | v3[4] | a2[5];
  v2[10] = v2[10] & 0xFCFF | a2[6];
  sub_80077AE(&v9);
  if ( v2 == (_WORD *)1073821696 )
    v5 = v11;
  else
    v5 = v10;
  if ( v2[6] & 0x8000 )
    v6 = 25 * v5 / (unsigned int)(2 * *(_DWORD *)v3);
  else
    v6 = 25 * v5 / (unsigned int)(4 * *(_DWORD *)v3);
  v7 = v6 - 100 * (v6 / 0x64 & 0xFFFFFFF);
  if ( v2[6] & 0x8000 )
    result = (8 * v7 + 50) / 0x64 & 7;
  else
    result = (16 * v7 + 50) / 0x64 & 0xF;
  v2[4] = 16 * (v6 / 0x64) | result;
  return result;
}

//----- (08009932) --------------------------------------------------------
int __fastcall sub_8009932(int result, int a2)
{
  __int16 v2; // r2

  if ( a2 )
    v2 = *(_WORD *)(result + 12) | 0x2000;
  else
    v2 = *(_WORD *)(result + 12) & 0xDFFF;
  *(_WORD *)(result + 12) = v2;
  return result;
}

//----- (0800994A) --------------------------------------------------------
int *__fastcall sub_800994A(int *a1, unsigned __int8 a2, int a3)
{
  int v3; // r4
  signed int v4; // r5
  int *result; // r0
  int v6; // r7

  v3 = a2 >> 5;
  v4 = 1 << (a2 & 0x1F);
  if ( v3 == 1 )
  {
    result = a1 + 3;
  }
  else if ( v3 == 2 )
  {
    result = a1 + 4;
  }
  else
  {
    result = a1 + 5;
  }
  if ( a3 )
    v6 = *result | v4;
  else
    v6 = *result & ~v4;
  *result = v6;
  return result;
}

//----- (08009A14) --------------------------------------------------------
int __fastcall sub_8009A14(int a1)
{
  return *(_WORD *)(a1 + 4) & 0x1FF;
}

//----- (08009B14) --------------------------------------------------------
BOOL __fastcall sub_8009B14(unsigned __int16 *a1, __int16 a2)
{
  int v2; // r5
  signed int v3; // r3
  int v4; // r3

  v2 = (unsigned __int8)a2 >> 5;
  v3 = 1 << (a2 & 0x1F);
  if ( v2 == 1 )
  {
    v4 = (unsigned __int16)(v3 & a1[6]);
  }
  else if ( v2 == 2 )
  {
    v4 = (unsigned __int16)(v3 & a1[8]);
  }
  else
  {
    v4 = (unsigned __int16)(v3 & a1[10]);
  }
  return v4 && (1 << SHIBYTE(a2)) & *a1;
}

//----- (08009BB2) --------------------------------------------------------
int __fastcall sub_8009BB2(int result)
{
  MEMORY[0x420E0020] = result;
  return result;
}

//----- (08009C68) --------------------------------------------------------
__int16 __fastcall sub_8009C68(__int16 result, int a2)
{
  if ( a2 )
    MEMORY[0x40002800] |= result;
  else
    MEMORY[0x40002800] &= ~result;
  return result;
}

//----- (08009C82) --------------------------------------------------------
int sub_8009C82()
{
  int result; // r0

  result = MEMORY[0x40002804] | 0x10;
  MEMORY[0x40002804] |= 0x10u;
  return result;
}

//----- (08009C94) --------------------------------------------------------
int sub_8009C94()
{
  int result; // r0

  result = MEMORY[0x40002804] & 0xFFEF;
  MEMORY[0x40002804] &= 0xFFEFu;
  return result;
}

//----- (08009CD4) --------------------------------------------------------
int sub_8009CD4()
{
  char v0; // r2^2
  __int16 v1; // r2

  sub_8009C82();
  MEMORY[0x40002808] = v0 & 0xF;
  MEMORY[0x4000280C] = v1;
  return sub_8009C94();
}

//----- (08009D20) --------------------------------------------------------
int sub_8009D20()
{
  int result; // r0

  do
    result = MEMORY[0x40002804];
  while ( !(MEMORY[0x40002804] & 0x20) );
  return result;
}

//----- (08009D30) --------------------------------------------------------
int sub_8009D30()
{
  int result; // r0

  MEMORY[0x40002804] &= 0xFFF7u;
  do
    result = MEMORY[0x40002804];
  while ( !(MEMORY[0x40002804] & 8) );
  return result;
}

//----- (08009DC2) --------------------------------------------------------
int __fastcall sub_8009DC2(int result)
{
  MEMORY[0x40002C04] = MEMORY[0x40002C04] & 0xFFFFFE7F | result;
  return result;
}

//----- (08009DD4) --------------------------------------------------------
char __fastcall sub_8009DD4(char result)
{
  MEMORY[0x40002C04] = result & 0x7F | MEMORY[0x40002C04] & 0xFFFFFF80;
  return result;
}

//----- (08009DF6) --------------------------------------------------------
signed int sub_8009DF6()
{
  signed int result; // r0

  result = 1;
  MEMORY[0x420580A4] = 1;
  return result;
}

//----- (08009DFE) --------------------------------------------------------
char __fastcall sub_8009DFE(char result)
{
  MEMORY[0x40002C00] = result & 0x7F;
  return result;
}

//----- (08009E0A) --------------------------------------------------------
int __fastcall sub_8009E0A(int result)
{
  MEMORY[0x40002C00] = result | 0x80;
  return result;
}

//----- (08009E20) --------------------------------------------------------
int sub_8009E20()
{
  int result; // r0

  result = 0;
  MEMORY[0x40002C08] = 0;
  return result;
}

//----- (08009E90) --------------------------------------------------------
signed int sub_8009E90()
{
  return 536871792;
}

//----- (08009E98) --------------------------------------------------------
void __noreturn sub_8009E98()
{
  __breakpoint(171);
  while ( 1 )
    ;
}

// ALL OK, 142 function(s) have been successfully decompiled
